server:
  port: 8085
  servlet: 
    context-path: /usuario-service

spring:
  application:
    name: usuario-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
    stream:
      default-binder: kafka            
      bindings:
        input:
          destination: topico.usuario
          group: output-group-1        
          content-type: application/json 
        input1:
          destination: topico.chamado
          group: output-group-2        
          content-type: application/json        
        Kafka:
          binder:
            zkNodes:localhost:9092
            brokers:localhost:29092          
  datasource:
    name: usuariodb    
    url: jdbc:postgresql://localhost:5432/usuario_db
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 60
      minimum-idle: 20
      pool-name: usuariodb
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    generate-ddl: true
    properties:
      hibernate: 
        format_sql: true
        ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

nome-servicos:
   aplicacao-chamado-service: chamado-service