server:
  port: 8083
  servlet: 
    context-path: /catalogo-service

spring:
  application:
    name: catalogo-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false        
    stream:
      default-binder: kafka            
      bindings:
        output:          
          destination: topico.usuario
          group: output-group-1
          content-type: application/json
        Kafka:
          binder:
            zkNodes:kafka
            brokers:kafka:29092
      
  datasource:
    name: catalogodb    
    url: jdbc:postgresql://postgres-filme-service/catalogo_db
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 60
      minimum-idle: 20
      pool-name: catalogodb
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    generate-ddl: true
    properties:
      hibernate: 
        format_sql: true
        ddl-auto: update           

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
  instance:
    preferIpAddress: true
    

  
    
