server:
  port: 8083
  servlet: 
    context-path: /catalogo-service

spring:
  application:
    name: catalogo-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
           
  datasource:
    name: catalogodb    
    url: jdbc:postgresql://localhost:5432/catalogo_db
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 60
      minimum-idle: 20
      pool-name: catalogodb
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    generate-ddl: true
    properties:
      hibernate: 
        format_sql: true
        ddl-auto: update           

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    

  
    
