server:
  port: 8084
  servlet: 
    context-path: /chamado-service

spring:
  application:
    name: chamado-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
    stream:
      default-binder: kafka            
      bindings:
        input:
          destination: topico.chamado
          group: output-group-1        
          content-type: application/json       
        Kafka:
          binder:
            zkNodes:localhost:9092
            brokers:localhost:29092   
  datasource:
    name: manutencaodb    
    url: jdbc:postgresql://localhost:5432/manutencao_db?createDatabaseIfNotExist=true&useSSL=false
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 60
      minimum-idle: 20
      pool-name: manutencaodb
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    properties:
      hibernate: 
        format_sql: true
        ddl-auto: create


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
